### ISSUE TITLE
the `between` in Award must not give anything when too small value

### ISSUE THREAD

**Issue by yegor256** [zerocracy/fbe#38]
This is how it should work:

  * `13` for `(between 5 20)`  -> 13
  * `3` for `(between 5 20)`  -> 0 (failure here)
  * `25` for `(between 5 20)`  -> 20
  * `-2` for `(between -10 -30)`  -> 0 (failure here)
  * `-15` for `(between -10 -30)`  -> -15
  * `-50` for `(between -10 -30)`  -> -30

Now it doesn't work like this.

**Comment by Suban05** [comment]
@yegor256 can you assign me?

**Comment by yegor256** [comment]
@Suban05 sure, go ahead

**Comment by yegor256** [comment]
@Suban05 you got it right

**Comment by Suban05** [comment]
@yegor256 thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.28`
