### ISSUE TITLE
Not need the brackets

### ISSUE THREAD

**Issue by Suban05** [zerocracy/fbe#47]
In some tests, the creation of an object with a hash transmission `Judges::Options.new({ 'testing' => true })` is possible without brackets. Let's remove them.

_Originally posted by @yegor256 in https://github.com/zerocracy/fbe/pull/43#discussion_r1695473374_

**Comment by Suban05** [comment]
@yegor256 can I create a pull request?

**Comment by yegor256** [comment]
@Suban05 just removing the brackets is not a solution. Someone else in the future will use them again. We should introduce a lint rule for that (in Rubocop), if we can. If we can't, there is no point in removing them in the code.

**Comment by Suban05** [comment]
@yegor256 unfortunately, we will not be able to configure rubocop in this way, because since Ruby 2.7, the existence of curly braces on the last argument has meaning. If I understand everything correctly, the rule we need has been removed (see [issue](https://github.com/rubocop/rubocop/issues/7641)).

**Comment by yegor256** [comment]
@Suban05 yes, indeed

**Comment by 0crat** [comment]
@Suban05 Thanks for submitting this ticket! However, as you see, it was not accepted by the team, which is sad. You've earned -20 points. By reporting bugs or suggesting enhacements, you help our project improve its quality. Please, don't be discouraged. Instead, try to be more careful next time, and [do not hesitate](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) to [report](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) bugs. Your running balance is [+91](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).
