### ISSUE TITLE
Interaction with the Github GraphQL API

### ISSUE THREAD

**Issue by Suban05** [zerocracy/fbe#61]
Let's add interaction with the Github GraphQL API via the [`graphql-client`](https://github.com/github-community-projects/graphql-client) library .
It will help us to get the information about the `resolved`/`unresolved` conversations in the pull requests.

Related to https://github.com/zerocracy/judges-action/issues/211

**Comment by Suban05** [comment]
@yegor256 can you assign me, please?

**Comment by yegor256** [comment]
@Suban05 go ahead!

**Comment by Suban05** [comment]
@yegor256 is there something wrong with the task? There is no sticker attached to this task. If the pull request for this issue is merged, this issue will be closed and I will be punished 😅

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.49`

**Comment by 0crat** [comment]
@Suban05 Hey there! 👋 Thanks for submitting the ticket, even though it wasn't accepted this time. As per our policy, there's a -16 point penalty, but don't let that discourage you! Your balance is still a healthy [+418](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep reporting [bugs](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) and suggesting improvements – it's crucial for our project's quality. Just be a bit more careful next time, and remember, [bugs are welcome](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html)! 🐞
